### ISSUE TITLE
No supporting normalizer found

### ISSUE THREAD

**Issue by metalmini** [ramsey/uuid-doctrine#53]
I am running in some trouble with the implementation of this bundle in a legacy application. The uuid's where always used but not with this bundle. 

I want to serialize some data that is being fetched using the querybuilder. 

```
        $datatable = $this->get('training.datatables.training');
        $results = $datatable->createDatatable();

        $serializer = $this->get('sg_datatables.serializer');

        $datatable->setData($serializer->serialize($results, 'json'));
```

The serialize function throws this exception:

```
Could not normalize object of type Ramsey\Uuid\Converter\Number\DegradedNumberConverter, no supporting normalizer found.
500 Internal Server Error - UnexpectedValueException
```

I have tried to cast the id field to string in some hack, but even that does not work.

Am i missing something here or is this "by design"?

**Comment by ramsey** [comment]
This appears to be an error from Doctrine. Can you show how you have your UUID properties configured on your model?

**Comment by metalmini** [comment]
Sorry for the late reply, holidays....

Anyway, this is the id property in my orm yml file
```
    id:
        id:
            type: uuid
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: Ramsey\Uuid\Doctrine\UuidGenerator
```
